foreign2host:
  foreign_pubs: ["/h1/odometry/filtered", "/h2/odometry/filtered"]
  foreign_tf:   ["map->h1_base", "map->h2_base", "map->h3_base"]
  foreign_ip: localhost
  foreign_port: 11311
  msgs_pub_freq: 40.0
  add_topic_prefix: /dick